# Data Quality Assessment

## Objective

Evaluate the quality of the dataset before performing data cleaning and exploratory data analysis.

### Quality Checks

- Missing Values
- Duplicate Records
- Class Imbalance
- Outlier Detection
- Data Types
- Feature Consistency
- Unique Values
- Memory Usage

In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/creditcard.csv")

## Missing Value Analysis

In [15]:
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing_values

        Missing Values  Percentage
Time                 0         0.0
V1                   0         0.0
V2                   0         0.0
V3                   0         0.0
V4                   0         0.0
V5                   0         0.0
V6                   0         0.0
V7                   0         0.0
V8                   0         0.0
V9                   0         0.0
V10                  0         0.0
V11                  0         0.0
V12                  0         0.0
V13                  0         0.0
V14                  0         0.0
V15                  0         0.0
V16                  0         0.0
V17                  0         0.0
V18                  0         0.0
V19                  0         0.0
V20                  0         0.0
V21                  0         0.0
V22                  0         0.0
V23                  0         0.0
V24                  0         0.0
V25                  0         0.0
V26                  0         0.0
V27                  0         0.0
V28                  0         0.0
Amount               0         0.0
Class                0         0.0

Observation

The dataset contains no missing values.

In [16]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 1081

In [17]:
duplicate_rows = df[df.duplicated()]

duplicate_rows.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
33,26.0,-0.529912,0.873892,1.347247,0.145457,0.414209,0.100223,0.711206,0.176066,-0.286717,...,0.046949,0.208105,-0.185548,0.001031,0.098816,-0.552904,-0.073288,0.023307,6.14,0
35,26.0,-0.535388,0.865268,1.351076,0.147575,0.433680,0.086983,0.693039,0.179742,-0.285642,...,0.049526,0.206537,-0.187108,0.000753,0.098117,-0.553471,-0.078306,0.025427,1.77,0
113,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
114,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
115,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0

In [18]:
class_counts = df["Class"].value_counts()

class_counts

Class
0    284315
1       492
Name: count, dtype: int64

In [19]:
class_percentage = (
    df["Class"].value_counts(normalize=True)*100
).round(4)

class_percentage

Class
0    99.8273
1     0.1727
Name: proportion, dtype: float64

In [20]:
unique_values = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique_values

        Unique Values
Time           124592
V1             275663
V2             275663
V3             275663
V4             275663
V5             275663
V6             275663
V7             275663
V8             275663
V9             275663
V10            275663
V11            275663
V12            275663
V13            275663
V14            275663
V15            275663
V16            275663
V17            275663
V18            275663
V19            275663
V20            275663
V21            275663
V22            275663
V23            275663
V24            275663
V25            275663
V26            275663
V27            275663
V28            275663
Amount          32767
Class               2

In [21]:
memory = (
    df.memory_usage(deep=True) / 1024**2
).round(2)

memory

Index     0.00
Time      2.17
V1        2.17
V2        2.17
V3        2.17
V4        2.17
V5        2.17
V6        2.17
V7        2.17
V8        2.17
V9        2.17
V10       2.17
V11       2.17
V12       2.17
V13       2.17
V14       2.17
V15       2.17
V16       2.17
V17       2.17
V18       2.17
V19       2.17
V20       2.17
V21       2.17
V22       2.17
V23       2.17
V24       2.17
V25       2.17
V26       2.17
V27       2.17
V28       2.17
Amount    2.17
Class     2.17
dtype: float64

In [22]:
print(
    f"Total Memory Usage : {memory.sum():.2f} MB"
)

Total Memory Usage : 67.27 MB

In [23]:
datatype_df = pd.DataFrame({
    "Column": df.columns,
    "Datatype": df.dtypes.values
})

datatype_df

    Column Datatype
0     Time  float64
1       V1  float64
2       V2  float64
3       V3  float64
4       V4  float64
5       V5  float64
6       V6  float64
7       V7  float64
8       V8  float64
9       V9  float64
10     V10  float64
11     V11  float64
12     V12  float64
13     V13  float64
14     V14  float64
15     V15  float64
16     V16  float64
17     V17  float64
18     V18  float64
19     V19  float64
20     V20  float64
21     V21  float64
22     V22  float64
23     V23  float64
24     V24  float64
25     V25  float64
26     V26  float64
27     V27  float64
28     V28  float64
29  Amount  float64
30   Class    int64

In [24]:
Q1 = df["Amount"].quantile(0.25)
Q3 = df["Amount"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers = df[
    (df["Amount"] < lower) |
    (df["Amount"] > upper)
]

print("Outliers :", len(outliers))

Outliers : 31904

# Data Quality Summary

## Findings

- No missing values.
- Duplicate transactions exist.
- Dataset is highly imbalanced.
- Amount column contains outliers.
- Data types are appropriate.
- Memory usage is acceptable.

## Next Step

Proceed to Data Cleaning.