# Data Cleaning

## Objective

Prepare a clean, consistent dataset for exploratory data analysis and machine learning.

### Cleaning Tasks

- Load Dataset
- Verify Missing Values
- Remove Duplicate Records
- Validate Data Types
- Investigate Outliers
- Save Clean Dataset

## Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/creditcard.csv")

In [3]:
rows, columns = df.shape

print(f"Rows    : {rows}")
print(f"Columns : {columns}")

Rows    : 284807
Columns : 31

In [4]:
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_values

        Missing Values  Percentage
Time                 0         0.0
V1                   0         0.0
V2                   0         0.0
V3                   0         0.0
V4                   0         0.0
V5                   0         0.0
V6                   0         0.0
V7                   0         0.0
V8                   0         0.0
V9                   0         0.0
V10                  0         0.0
V11                  0         0.0
V12                  0         0.0
V13                  0         0.0
V14                  0         0.0
V15                  0         0.0
V16                  0         0.0
V17                  0         0.0
V18                  0         0.0
V19                  0         0.0
V20                  0         0.0
V21                  0         0.0
V22                  0         0.0
V23                  0         0.0
V24                  0         0.0
V25                  0         0.0
V26                  0         0.0
V27                  0         0.0
V28                  0         0.0
Amount               0         0.0
Class                0         0.0

### Observation

No missing values were found in the dataset.

Therefore, no imputation or deletion is required.

In [5]:
duplicates = df.duplicated().sum()

print(f"Duplicate Transactions : {duplicates}")

Duplicate Transactions : 1081

In [6]:
duplicate_transactions = df[df.duplicated()]

duplicate_transactions.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
33,26.0,-0.529912,0.873892,1.347247,0.145457,0.414209,0.100223,0.711206,0.176066,-0.286717,...,0.046949,0.208105,-0.185548,0.001031,0.098816,-0.552904,-0.073288,0.023307,6.14,0
35,26.0,-0.535388,0.865268,1.351076,0.147575,0.433680,0.086983,0.693039,0.179742,-0.285642,...,0.049526,0.206537,-0.187108,0.000753,0.098117,-0.553471,-0.078306,0.025427,1.77,0
113,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
114,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
115,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0

In [7]:
df = df.drop_duplicates()

In [8]:
print("Remaining duplicates:", df.duplicated().sum())

Remaining duplicates: 0

In [9]:
rows, columns = df.shape

print(f"Rows after cleaning    : {rows}")
print(f"Columns after cleaning : {columns}")

Rows after cleaning    : 283726
Columns after cleaning : 31

In [10]:
datatype_df = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values
})

datatype_df

    Column Data Type
0     Time   float64
1       V1   float64
2       V2   float64
3       V3   float64
4       V4   float64
5       V5   float64
6       V6   float64
7       V7   float64
8       V8   float64
9       V9   float64
10     V10   float64
11     V11   float64
12     V12   float64
13     V13   float64
14     V14   float64
15     V15   float64
16     V16   float64
17     V17   float64
18     V18   float64
19     V19   float64
20     V20   float64
21     V21   float64
22     V22   float64
23     V23   float64
24     V24   float64
25     V25   float64
26     V26   float64
27     V27   float64
28     V28   float64
29  Amount   float64
30   Class     int64

In [11]:
Q1 = df["Amount"].quantile(0.25)
Q3 = df["Amount"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [12]:
outliers = df[
    (df["Amount"] < lower_bound) |
    (df["Amount"] > upper_bound)
]

print(f"Potential Outliers : {len(outliers)}")

Potential Outliers : 31685

### Observation

The Amount feature contains several potential outliers.

These values are **not removed** because unusually large transactions may represent legitimate fraud cases.

Removing them could reduce the model's ability to detect fraudulent activity.

## Save Clean Dataset

In [13]:
df.to_csv(
    "../data/processed/cleaned_creditcard.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

## Final Validation

In [14]:
print("Final Dataset Shape")

print(df.shape)

print("\nMissing Values")

print(df.isnull().sum().sum())

print("\nDuplicate Rows")

print(df.duplicated().sum())

Final Dataset Shape
(283726, 31)

Missing Values
0

Duplicate Rows
0

# Cleaning Summary

## Cleaning Steps Performed

- Verified missing values
- Removed duplicate transactions
- Verified data types
- Investigated outliers
- Saved cleaned dataset

## Result

The cleaned dataset is now ready for exploratory data analysis.

The cleaned dataset stored in:

data/processed/cleaned_creditcard.csv