# Feature Engineering

## Objective

Prepare the cleaned credit card transaction dataset for machine learning.

### Tasks

- Load cleaned dataset
- Create useful features
- Split features and target
- Scale numerical data
- Handle class imbalance
- Save preprocessing artifacts

In [22]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import joblib

In [23]:
df = pd.read_csv("../data/processed/cleaned_creditcard.csv")

In [24]:
print(df.shape)

df.head()

(283726, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [25]:
X = df.drop("Class", axis=1)

y = df["Class"]

The machine learning model learns from the features (X) and predicts the target (y).

X → Transaction information

y → Fraud (0 or 1)

In [26]:
summary = pd.DataFrame({
    "Data Type": X.dtypes,
    "Missing Values": X.isnull().sum(),
    "Unique Values": X.nunique()
})

summary

       Data Type  Missing Values  Unique Values
Time     float64               0         124592
V1       float64               0         275663
V2       float64               0         275663
V3       float64               0         275663
V4       float64               0         275663
V5       float64               0         275663
V6       float64               0         275663
V7       float64               0         275663
V8       float64               0         275663
V9       float64               0         275663
V10      float64               0         275663
V11      float64               0         275663
V12      float64               0         275663
V13      float64               0         275663
V14      float64               0         275663
V15      float64               0         275663
V16      float64               0         275663
V17      float64               0         275663
V18      float64               0         275663
V19      float64               0         275663
V20      float64               0         275663
V21      float64               0         275663
V22      float64               0         275663
V23      float64               0         275663
V24      float64               0         275663
V25      float64               0         275663
V26      float64               0         275663
V27      float64               0         275663
V28      float64               0         275663
Amount   float64               0          32767

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

## Observation

The dataset has been split using stratified sampling.

This preserves the fraud-to-genuine ratio in both the training and testing datasets, which is critical for imbalanced classification problems.

In [28]:
print("Training Set :", X_train.shape)

print("Testing Set :", X_test.shape)

Training Set : (226980, 30)
Testing Set : (56746, 30)

In [29]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

We fit the scaler only on the training dataset to avoid data leakage.

The testing dataset is transformed using the same scaler.

In [30]:
feature_names = X.columns.tolist()

print(feature_names)

['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']

In [31]:
print(X_train_scaled[:5])

[[ 1.04549909  1.14719836 -1.04203246 -1.42882122 -1.81782372  0.72719752
   2.69567651 -1.48930967  0.73574582 -1.1527044   1.46294508 -0.23144624
  -0.71106413  0.36640847 -0.3267679   0.3107816  -0.66265092  0.4532502
  -0.21858679 -0.39183752 -0.42719557 -0.20857295 -0.0682055   0.44537866
   1.13020245 -0.42036292 -0.33128128  0.09278213 -0.15619266 -0.22943372]
 [-0.29869002 -0.67791131  0.99194846  0.39466759 -0.02564188 -0.30119792
  -0.72824     0.17561517  0.62906964 -1.15629021 -0.44768035  1.41072091
   1.77590449  1.26254666  0.90568792 -0.29213577  0.44924302 -0.3139793
  -0.41300753  0.48143447 -0.08983279 -0.3322481  -1.30714055  0.51803572
   0.85106892 -1.36733752 -0.55425458 -0.04986389  0.15383143 -0.33119698]
 [ 0.67839667  0.97765362  0.0162054  -1.38670055  0.09268839  0.85061266
   0.45882253 -0.01987242  0.15436983  0.26205551 -0.46178004  1.50481822
   1.04711116  0.4792321  -0.72078502  1.05351845 -0.31917661  0.94169101
  -0.18983101 -1.2233426  -0.27797265  0.40504007  1.51273202 -0.07134972
  -2.78890486  0.20292382  0.01547874  0.11132947 -0.16581986 -0.29880852]
 [-0.07492874  0.92756117  0.19526071  0.20873558  2.73985478  0.03200327
   0.77234847 -0.61353184  0.19999866  0.62547844  1.07051262  1.31274417
  -1.78875715  2.19263796  1.30071597 -2.22905422  1.5369989  -0.56286224
   0.98234457 -2.08223896 -0.30109116  0.19079291  0.96684563  0.27855944
   1.16034766 -0.40789313 -0.02144686 -0.04972425 -0.11958202 -0.28924659]
 [-1.3767283   0.69521762 -0.67611774  0.36366111 -1.09081196 -0.88250663
   0.20961844 -1.0026201   0.18224302 -1.91160982  1.39301892  1.70589606
   0.01445969  0.33245749 -0.04506887  0.51650912 -0.75663589  0.93480838
  -0.76873008 -0.72815574 -0.47706584 -0.4735758  -0.87872188  0.40432925
  -0.568164   -0.12370514 -0.91388177  0.15577597  0.0372903  -0.26198495]]

In [32]:
print(y_train.value_counts())

Class
0    226602
1       378
Name: count, dtype: int64

The dataset is highly imbalanced.

However, balancing techniques such as SMOTE will only be applied during model training to avoid information leakage.

In [33]:
joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

['../models/scaler.pkl']

In [34]:
print("Scaler saved successfully.")

Scaler saved successfully.

# Feature Engineering Summary

## Completed

- Loaded cleaned dataset
- Separated features and target
- Split training and testing datasets
- Standardized feature values
- Saved processed datasets
- Saved scaler

## Next Step

Train multiple machine learning models using the prepared datasets.